---

- name: Install nagios needed nrpe packages
  tags: monitoring
  yum: name={{ item }} state=latest
  with_items:
    - nrpe
    - nagios-plugins
    - nagios-plugins-disk

- name: Copy nrpe configuration file on api host
  tags: monitoring
  copy: src=argo-web-api.cfg
        dest={{ nrpe_conf_path }}/argo-web-api.cfg backup=yes
        owner=root group=root mode=0644
  notify: restart nrpe
  when: inventory_hostname in groups.webapi and inventory_hostname not in groups.standalone

- name: Copy nrpe configuration file on consumer host
  tags: monitoring
  copy: src=argo-consumer.cfg
        dest={{ nrpe_conf_path }}/argo-consumer.cfg backup=yes
        owner=root group=root mode=0644
  notify: restart nrpe
  when: inventory_hostname in groups.standalone

- name: Modify nrpe configuration itself
  tags: monitoring
  lineinfile: dest=/etc/nagios/nrpe.cfg
              regexp="^allowed_hosts="
              line="allowed_hosts={{ nrpe_allowed_hosts }}"
              state=present
              backup=yes
  notify: restart nrpe

- name: Start and enable nrpe service
  tags: monitoring
  service: name=nrpe state=started enabled=yes
